name: Linting

on:
  push:
    branches: [ "Projects" ]
  pull_request:
    branches: [ "Projects" ]

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest
        
        steps:
          - name: Checout repository
            uses: actions/checkout@v4

          - name: Build python environment
            uses: actions/setup-python@v1
            with:
                python-version: "3.11"

          - name: Install linting dependencies
            run: pip install black flake8 mypy isort djlint

          - name: Run lint checks
            uses: wearerequired/lint-action@v2
            # TODO: Script for above packages
